import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { numberToWordsINR, money } from "@/lib/calc";

// Renders a Tally-style GST invoice and returns a PDF data URI string for on-screen preview.
export function buildInvoicePdf({ shop, draft, totals, customer }) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const M = 40;
  let y = 44;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(49, 46, 129);
  doc.text(shop?.name || "DukanSaathi", M, y);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(90);
  y += 16;
  if (shop?.address) { doc.text(shop.address, M, y); y += 12; }
  if (shop?.phone) { doc.text("Ph: " + shop.phone, M, y); y += 12; }
  if (shop?.gstEnabled && shop?.gstin) { doc.text("GSTIN: " + shop.gstin, M, y); y += 12; }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(20);
  const title = draft.type === "purchase" ? "PURCHASE / STOCK-IN" : (shop?.gstEnabled ? "TAX INVOICE" : "INVOICE");
  doc.text(title, W - M, 48, { align: "right" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(80);
  doc.text("Invoice No: " + (draft.invoiceNo || "DRAFT"), W - M, 66, { align: "right" });
  doc.text("Date: " + new Date(draft.date || Date.now()).toLocaleDateString("en-IN"), W - M, 80, { align: "right" });

  y = Math.max(y, 96) + 6;
  doc.setDrawColor(220);
  doc.line(M, y, W - M, y);
  y += 16;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(30);
  doc.text(draft.type === "purchase" ? "Supplier:" : "Bill To:", M, y);
  doc.setFont("helvetica", "normal");
  y += 13;
  doc.text(customer?.name || draft.customerName || "Walk-in Customer", M, y);
  if (customer?.phone) { y += 12; doc.text("Ph: " + customer.phone, M, y); }
  if (customer?.siteNote) { y += 12; doc.text("Site: " + customer.siteNote, M, y); }
  y += 10;

  const body = (draft.items || []).map((it, i) => [
    i + 1,
    it.name + (it.unit ? `  (${it.unit})` : ""),
    String(it.qty),
    money(it.rate),
    money((Number(it.qty) || 0) * (Number(it.rate) || 0)),
  ]);

  autoTable(doc, {
    startY: y + 6,
    head: [["#", "Item", "Qty", "Rate", "Amount"]],
    body,
    theme: "grid",
    headStyles: { fillColor: [49, 46, 129], textColor: 255, fontSize: 9 },
    bodyStyles: { fontSize: 9, textColor: 40 },
    columnStyles: {
      0: { cellWidth: 26, halign: "center" },
      2: { halign: "center", cellWidth: 50 },
      3: { halign: "right", cellWidth: 80 },
      4: { halign: "right", cellWidth: 90 },
    },
    margin: { left: M, right: M },
  });

  let yy = doc.lastAutoTable.finalY + 16;
  const rx = W - M;
  const lx = W - M - 220;
  const row = (label, val, bold) => {
    doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.setFontSize(bold ? 11 : 9);
    doc.setTextColor(bold ? 20 : 70);
    doc.text(label, lx, yy);
    doc.text(val, rx, yy, { align: "right" });
    yy += bold ? 18 : 14;
  };
  row("Subtotal", money(totals.subtotal));
  if (totals.discountOff > 0) row("Discount", "- " + money(totals.discountOff));
  if (totals.gstRate > 0) row(`GST @ ${totals.gstRate}%`, money(totals.gstAmount));
  doc.setDrawColor(200); doc.line(lx, yy - 6, rx, yy - 6);
  row("Grand Total", money(totals.grandTotal), true);

  yy += 4;
  doc.setFont("helvetica", "italic");
  doc.setFontSize(8.5);
  doc.setTextColor(90);
  const wl = doc.splitTextToSize("In words: " + numberToWordsINR(totals.grandTotal), W - 2 * M);
  doc.text(wl, M, yy);
  yy += wl.length * 11 + 6;

  (draft.payments || []).forEach((p) => {
    doc.setFont("helvetica", "normal"); doc.setFontSize(9); doc.setTextColor(70);
    doc.text(`Paid via ${p.mode}: ${money(p.amount)}`, M, yy); yy += 12;
  });
  if (totals.amountPending > 0.5) {
    doc.setFont("helvetica", "bold"); doc.setTextColor(225, 29, 72);
    doc.text(`Pending (Udhari): ${money(totals.amountPending)}`, M, yy); yy += 14;
  }

  if (totals.ewayRequired) {
    doc.setFont("helvetica", "bold"); doc.setFontSize(9); doc.setTextColor(217, 119, 6);
    doc.text("* E-way bill required (invoice value >= Rs 50,000)", M, yy + 4);
    yy += 16;
  }

  doc.setFont("helvetica", "normal"); doc.setFontSize(8); doc.setTextColor(140);
  doc.text("Generated by DukanSaathi — Bolo, bill banao, stock sambhalo", M, doc.internal.pageSize.getHeight() - 30);

  return doc.output("datauristring");
}
