import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { money, fmtDate, fmtTime } from "@/lib/calc";

// Printable daily summary (F6): sales, cash/online collected, udhari, expenses, net cash.
export function buildDailySummaryPdf({ shop, dateISO, stats, expenses }) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const M = 40;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(49, 46, 129);
  doc.text(shop?.name || "DukanSaathi", M, 48);
  doc.setFontSize(12);
  doc.setTextColor(30);
  doc.text("Daily Summary", M, 70);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(90);
  doc.text(fmtDate(dateISO), W - M, 70, { align: "right" });

  autoTable(doc, {
    startY: 90,
    theme: "grid",
    head: [["Metric", "Amount"]],
    headStyles: { fillColor: [49, 46, 129], textColor: 255 },
    bodyStyles: { fontSize: 10 },
    columnStyles: { 1: { halign: "right", cellWidth: 160 } },
    body: [
      ["Sales Revenue", money(stats.salesRevenue)],
      ["Cash Collected", money(stats.cashCollected)],
      ["Online Collected", money(stats.onlineCollected)],
      ["Udhari Given Today", money(stats.udhariAdded)],
      ["Udhari Collected Today", money(stats.udhariCollected)],
      ["Cash Expenses", money(stats.cashExpenses ?? 0)],
      ["Online Expenses", money(stats.onlineExpenses ?? 0)],
      ["Net Cash Position", money(stats.netCash)],
      ["Net Online Position", money(stats.netOnline ?? 0)],
    ],
    margin: { left: M, right: M },
  });

  let y = doc.lastAutoTable.finalY + 20;
  if (expenses && expenses.length) {
    doc.setFont("helvetica", "bold"); doc.setFontSize(11); doc.setTextColor(30);
    doc.text("Expenses Detail", M, y);
    autoTable(doc, {
      startY: y + 8,
      theme: "striped",
      head: [["Time", "Note", "Mode", "Amount"]],
      headStyles: { fillColor: [234, 88, 12], textColor: 255 },
      body: expenses.map((e) => [fmtTime(e.date), e.note || "-", e.mode, money(e.amount)]),
      columnStyles: { 0: { cellWidth: 70 }, 3: { halign: "right" } },
      margin: { left: M, right: M },
    });
  }

  doc.setFont("helvetica", "normal"); doc.setFontSize(8); doc.setTextColor(140);
  doc.text("Generated by DukanSaathi", M, doc.internal.pageSize.getHeight() - 30);
  return doc.output("datauristring");
}
